version: 0.1

environment_variables:
phases:
  install:
    commands:
      - echo Installing Pkgs and Gems...
      - /bin/sh ./install.sh
  pre_build:
    commands:
      - echo Preparing started on `date`
      - ./bin/rake db:migrate 
  build:
    commands:
      - echo Test started on `date`
      - bundle exec rake test 
  post_build:
    commands:
      - echo Build completed on `date`
      - git archive --format=zip HEAD > redmine-latest.zip
